---
title: "Proyecto diplomado exploración de datos"
author: "Jonathan Maureira"
date: "2023-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#install.packages("dplyr")
library(dplyr)
library(readxl)
#install.packages("tidyr")
library(tidyr)
library(ggplot2)
library(gridExtra)
```
# Titulo: Cataratas en Salar


## Objetivos: 
- Se asociara el indice de desarrollo de las cataratas como indicador de severidad productiva.
- Se espera que peces con mayor grado de cataratas, tengas un indice de condicion menor.

## Base de datos y analisis exploratorios

1° Importar base de datos
```{r}
B_D_CAT <- read_excel("B_D_CAT.xlsx", col_types = c("text", 
                                                    "date", "numeric", "numeric", "numeric", 
                                                    "numeric", "numeric", "numeric"))
# View(B_D_CAT)
```
2° Identificar datos atípicos, duplicados o faltantes (NA) con summary
```{r}
summary(B_D_CAT)
```


